import { Category, Product } from "./types";

export const CATEGORIES: Category[] = [
  { id: "1", name: "Salon", slug: "salon", description: "Canapés, fauteuils, tables basses", product_count: 0 },
  { id: "2", name: "Chambre", slug: "chambre", description: "Lits, armoires, tables de chevet", product_count: 0 },
  { id: "3", name: "Salle à manger", slug: "salle-a-manger", description: "Tables, chaises, buffets", product_count: 0 },
  { id: "4", name: "Bureau", slug: "bureau", description: "Bureaux, chaises de bureau, étagères", product_count: 0 },
  { id: "5", name: "Extérieur", slug: "exterieur", description: "Mobilier de jardin et terrasse", product_count: 0 },
  { id: "6", name: "Décoration", slug: "decoration", description: "Tapis, luminaires, coussins", product_count: 0 },
];

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "SALON 8 PLACES",
    slug: "salon-8-places",
    description: "Canapé confortable 8 places en tissu de qualité supérieure. Design moderne et élégant, parfait pour votre salon.",
    price: 285000,
    original_price: 350000,
    category_id: "1",
    images: ["/images/products/p1_1.jpg","/images/products/p1_2.jpg","/images/products/p1_3.jpg","/images/products/p1_4.jpg","/images/products/p1_5.jpg","/images/products/p1_6.jpg"],
    stock_status: "in_stock",
    delivery_days: 3,
    is_featured: true,
    is_new: false,
    style: "Moderne",
    material: "Tissu",
    dimensions: "220 x 85 x 90 cm",
    created_at: "2024-01-01",
  },
  {
    id: "2",
    name: "Canapé 8 places en tissu",
    slug: "salon-8-places-2",
    description: "Canapé confortable 8 places en tissu de qualité supérieure. Design moderne et élégant, parfait pour votre salon.",
    price: 420000,
    category_id: "2",
    images: ["/images/products/p2_1.jpg","/images/products/p2_2.jpg","/images/products/p2_3.jpg","/images/products/p2_4.jpg","/images/products/p2_5.jpg","/images/products/p2_6.jpg","/images/products/p2_7.jpg","/images/products/p2_8.jpg","/images/products/p2_9.jpg"],
    stock_status: "in_stock",
    delivery_days: 5,
    is_featured: true,
    is_new: true,
    style: "Classique",
    material: "Bois massif",
    dimensions: "160 x 200 cm",
    created_at: "2024-01-15",
  },
  {
    id: "3",
    name: "Meubles 100% Turquie",
    slug: "meubles-100-turquie",
    description: "Embellissez votre espace de vie à coût abordable avec de la qualité uniquement chez les Ets İstanbul Meubles Niger. Nous vous proposons des meubles 100% Turquie, de qualité supérieure, à des prix compétitifs. Découvrez notre large gamme de produits pour tous les goûts et styles.",
    price: 1950000,
    original_price: 2400000,
    category_id: "3",
    images: ["/images/products/p3_1.jpg","/images/products/p3_2.jpg","/images/products/p3_3.jpg","/images/products/p3_4.jpg"],
    stock_status: "in_stock",
    delivery_days: 3,
    is_featured: true,
    is_new: false,
    style: "Moderne",
    material: "Verre et métal",
    dimensions: "180 x 90 x 75 cm",
    created_at: "2024-02-01",
  },
  {
    id: "4",
    name: "Ensemble de chambre complète",
    slug: "ensemble-chambre-complete",
    description: "Ensemble de chambre complète pour la magnifique mariée que vous êtes 😍🥰 Autant que le choix du conjoint 😅, le choix de vos meubles est d'une importance capitale 👌🏽 Faites le bon choix et prenez vos meubles chez nous 🤩",
    price: 1450000,
    category_id: "4",
    images: ["/images/products/p4_1.jpg","/images/products/p4_2.jpg","/images/products/p4_3.jpg"],
    stock_status: "on_order",
    delivery_days: 14,
    is_featured: false,
    is_new: true,
    style: "Moderne",
    material: "MDF et métal",
    dimensions: "160 x 120 x 75 cm",
    created_at: "2024-02-15",
  },
  {
    id: "5",
    name: "table à manger 6 places",
    slug: "table-a-manger-6-places",
    description: "Table à manger spacieuse pour 6 personnes. Plateau en verre trempé sur structure en métal noir.",
    price: 165000,
    original_price: 195000,
    category_id: "1",
    images: ["/images/products/p5_1.jpg","/images/products/p5_2.jpg","/images/products/p5_3.jpg"],
    stock_status: "in_stock",
    delivery_days: 3,
    is_featured: true,
    is_new: false,
    style: "Moderne",
    material: "Simili-cuir",
    dimensions: "85 x 90 x 105 cm",
    created_at: "2024-03-01",
  },
  {
    id: "6",
    name: "table à manger 6 places",
    slug: "table-a-manger-6-places",
    description: "Table à manger trsès spacieuse pour 6 personnes. Plateau en verre trempé sur structure en métal noir.",
    price: 255000,
    category_id: "1",
    images: ["/images/products/p6_1.jpg","/images/products/p6_2.jpg","/images/products/p6_3.jpg","/images/products/p6_4.jpg"],
    stock_status: "in_stock",
    delivery_days: 5,
    is_featured: false,
    is_new: true,
    style: "Classique",
    material: "MDF laqué",
    dimensions: "180 x 60 x 220 cm",
    created_at: "2024-03-10",
  },
  {
    id: "7",
    name: "ensemble de  chambre",
    slug: "ensemble-de-chambre",
    description: "Ensemble de chambre complet comprenant un lit, une armoire et deux tables de chevet. Design élégant et moderne pour un confort optimal. Idéal pour créer une ambiance chaleureuse et accueillante dans votre chambre.",
    price: 620000,
    original_price: 750000,
    category_id: "1",
    images: ["/images/products/p7_1.jpg","/images/products/p7_2.jpg","/images/products/p7_3.jpg","/images/products/p7_4.jpg","/images/products/p7_5.jpg"],
    stock_status: "in_stock",
    delivery_days: 5,
    is_featured: true,
    is_new: false,
    style: "Baroque",
    material: "Velours et bois",
    dimensions: "Canapé : 210 x 90 x 95 cm",
    created_at: "2024-04-01",
  },
  {
    id: "8",
    name: "moquette de luxe",
    slug: "moquette-de-luxe",
    description: "Moquette de luxe en fibres naturelles, idéale pour un confort optimal dans votre salon ou chambre.",
    price: 75000,
    original_price: 95000,
    category_id: "2",
    images: ["/images/products/p8_1.jpg","/images/products/p8_2.jpg","/images/products/p8_3.jpg"],
    stock_status: "in_stock",
    delivery_days: 3,
    is_featured: false,
    is_new: true,
    style: "Moderne",
    material: "MDF et marbre",
    dimensions: "50 x 40 x 55 cm",
    created_at: "2024-04-10",
  },
  {
    id: "9",
    name: "Du salon à la chambre, le confort ultime",
    slug: "du-salon-a-la-chambre-le-confort-ultime",
    description: "Du salon à la chambre, le confort ultime. Découvrez notre sélection de meubles de qualité pour un intérieur élégant et fonctionnel.",
    price: 7500000,
    original_price: 9500000,
    category_id: "2",
    images: ["/images/products/p9_1.jpg","/images/products/p9_2.jpg","/images/products/p9_3.jpg","/images/products/p9_4.jpg"],
    stock_status: "in_stock",
    delivery_days: 3,
    is_featured: false,
    is_new: true,
    style: "Moderne",
    material: "MDF et marbre",
    dimensions: "50 x 40 x 55 cm",
    created_at: "2024-04-10", 
  },
  {
    id: "10",
    name: "interieur de luxe",
    slug: "interieur-de-luxe",
    description: "Un intérieur de luxe pour un confort optimal dans votre maison.",
    price: 7500000,
    original_price: 9500000,
    category_id: "2",
    images: ["/images/products/p10_1.jpg","/images/products/p10_2.jpg","/images/products/p10_3.jpg","/images/products/p10_4.jpg"],
    stock_status: "in_stock",
    delivery_days: 3,
    is_featured: false,
    is_new: true,
    style: "Moderne",
    material: "MDF et marbre",
    dimensions: "50 x 40 x 55 cm",
    created_at: "2024-04-10",
  },
  {
    id: "11",
    name: "interieur complet de luxe",
    slug: "interieur-complet-de-luxe",
    description: "Un intérieur complet de luxe pour un confort optimal dans votre maison. Découvrez notre sélection de meubles de qualité pour un intérieur élégant et fonctionnel.",
    price: 7500000,
    original_price: 9500000,
    category_id: "2",
    images: ["/images/products/p11_1.jpg","/images/products/p11_2.jpg","/images/products/p11_3.jpg"],
    stock_status: "in_stock",
    delivery_days: 3,
    is_featured: false,
    is_new: true,
    style: "Moderne",
    material: "MDF et marbre",
    dimensions: "50 x 40 x 55 cm",
    created_at: "2024-04-10",
  },
  {
    id: "12",
    name: "terrasse, balcon, jardin",
    slug: "terrasse-balcon-jardin",
    description: "Créez une ambiance chaleureuse et accueillante dans votre espace extérieur avec notre sélection de meubles pour terrasse, balcon et jardin. Profitez du confort et de l'élégance pour vos moments de détente en plein air.",
    price: 75000,
    original_price: 95000,
    category_id: "2",
    images: ["/images/products/p12_1.jpg","/images/products/p12_2.jpg","/images/products/p12_3.jpg","/images/products/p12_4.jpg"],
    stock_status: "in_stock",
    delivery_days: 3,
    is_featured: false,
    is_new: true,
    style: "Moderne",
    material: "MDF et marbre",
    dimensions: "50 x 40 x 55 cm",
    created_at: "2024-04-10",
  },
  {
    id: "13",
    name: "chambre a coucher intérieur",
    slug: "chambre-a-coucher-intérieur",
    description: "Un intérieur complet de luxe pour un confort optimal dans votre maison. Découvrez notre sélection de meubles de qualité pour un intérieur élégant et fonctionnel.",
    price: 7500000,
    original_price: 9500000,
    category_id: "2",
    images: ["/images/products/p13_1.jpg","/images/products/p13_2.jpg","/images/products/p13_3.jpg","/images/products/p13_4.jpg","/images/products/p13_5.jpg"],
    stock_status: "in_stock",
    delivery_days: 3,
    is_featured: false,
    is_new: true,
    style: "Moderne",
    material: "MDF et marbre",
    dimensions: "50 x 40 x 55 cm",
    created_at: "2024-04-10",
  },
  {
    id: "14",
    name: "salon de luxe et table de chevet",
    slug: "salon-de-luxe-et-table-de-chevet",
    description: "Un salon de luxe avec une table de chevet pour un confort optimal dans votre maison.",
    price: 2000000,
    original_price: 25000000,
    category_id: "2",
    images: ["/images/products/p14_1.jpg","/images/products/p14_2.jpg"],
    stock_status: "in_stock",
    delivery_days: 3,
    is_featured: false,
    is_new: true,
    style: "Moderne",
    material: "MDF et marbre",
    dimensions: "50 x 40 x 55 cm",
    created_at: "2024-04-10",
  },
  {
    id: "15",
    name: "salon de luxe et table",
    slug: "salon-de-luxe-et-table",
    description: "Un salon de luxe avec une table pour un confort optimal dans votre maison.",
    price: 2000000,
    original_price: 25000000,
    category_id: "2",
    images: ["/images/products/p15_1.jpg","/images/products/p15_2.jpg","/images/products/p15_3.jpg","/images/products/p15_4.jpg","/images/products/p15_5.jpg"],
    stock_status: "in_stock",
    delivery_days: 3,
    is_featured: false,
    is_new: true,
    style: "Moderne",
    material: "MDF et marbre",
    dimensions: "50 x 40 x 55 cm",
    created_at: "2024-04-10",
  },
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("fr-FR").format(price) + " FCFA";
}

export function getDiscountPercent(price: number, originalPrice: number): number {
  return Math.round(((originalPrice - price) / originalPrice) * 100);
}
